apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: litellm
type: Opaque
data:
  host: bGl0ZWxsbS1wb3N0Z3Jlcy1ydy5saXRlbGxtLnN2Yy5jbHVzdGVyLmxvY2Fs # litellm-postgres-rw.litellm.svc.cluster.local
  password: cGFzc3dvcmQxMjM= # password123 (should match what you set in postgres-cluster.yaml)
  username: bGl0ZWxsbQ== # litellm
  dbname: bGl0ZWxsbQ== # litellm