{{- if .Values.litellm.masterKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.litellm.masterKey.secretName }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.litellm.masterKey.secretKey }}: {{ .Values.litellm.masterKey.value | b64enc }}
{{- end }} 
