{{- if .Values.operator.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.operator.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.operator.metrics.service.type }}
  ports:
  - port: {{ .Values.operator.metrics.service.port }}
    targetPort: {{ .Values.operator.metrics.service.targetPort }}
    protocol: TCP
    name: metrics
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
