# This rule is not used by the project litellm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over litellm.litellm.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: litellm-operator
    app.kubernetes.io/managed-by: kustomize
  name: litellm-litellminstance-admin-role
rules:
- apiGroups:
  - litellm.litellm.ai
  resources:
  - litellminstances
  verbs:
  - '*'
- apiGroups:
  - litellm.litellm.ai
  resources:
  - litellminstances/status
  verbs:
  - get
