# permissions for end users to view teammemberassociations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: litellm-operator
    app.kubernetes.io/managed-by: kustomize
  name: teammemberassociation-viewer-role
rules:
- apiGroups:
  - auth.litellm.ai
  resources:
  - teammemberassociations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.litellm.ai
  resources:
  - teammemberassociations/status
  verbs:
  - get
