# permissions for end users to view users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: litellm-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-viewer-role
rules:
- apiGroups:
  - auth.litellm.ai
  resources:
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.litellm.ai
  resources:
  - users/status
  verbs:
  - get
