apiVersion: auth.litellm.ai/v1alpha1
kind: TeamMemberAssociation
metadata:
  labels:
    app.kubernetes.io/name: litellm-operator
    app.kubernetes.io/managed-by: kustomize
  name: teammemberassociation-sample
spec:
  role: user
  teamAlias: my-team
  userEmail: my-user@example.com
