apiVersion: auth.litellm.ai/v1alpha1
kind: Team
metadata:
  name: ai-team
spec:
  teamAlias: ai-team
  models:
    - gpt-4o
  connectionRef:
    instanceRef:
      name: litellm-example
      namespace: litellm
    
