apiVersion: auth.litellm.ai/v1alpha1
kind: TeamMemberAssociation
metadata:
  name: bob-ai-team
  namespace: litellm
spec:
  connectionRef:
    instanceRef:
      name: litellm-example
      namespace: litellm
  role: user
  teamAlias: ai-team
  userEmail: bob@example.com
