apiVersion: auth.litellm.ai/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: litellm-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  userEmail: my-user@example.com
  userAlias: my-user-alias
  userRole: customer
  keyAlias: my-user-key-alias
  autoCreateKey: true
  models:
    - gpt-4o
  teams:
    - my-team
  maxBudget: "10"
  budgetDuration: 1h
