## Append samples of your project ##
resources:
- namespace.yaml
- auth_v1alpha1_virtualkey.yaml
- auth_v1alpha1_user.yaml
- auth_v1alpha1_team.yaml
- auth_v1alpha1_teammemberassociation.yaml
- litellm_v1alpha1_litellminstance.yaml
- litellm_v1alpha1_model.yaml
- model_credentials.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
