apiVersion: litellm.litellm.ai/v1alpha1
kind: LiteLLMInstance
metadata:
  name: litellm-example
  namespace: litellm
spec:
  redisSecretRef:
    nameRef:  redis-secret
    keys:
      hostSecret: host
      portSecret: port
      passwordSecret: password
  databaseSecretRef:
    nameRef:  postgres-secret
    keys:
      hostSecret: host
      passwordSecret: password
      usernameSecret: username
      dbnameSecret: dbname
  models:
  - modelName: claude-opus
    requiresAuth: true
    identifier: claude-opus4.1
    modelCredentials:
      nameRef: bedrock-model-credentials
      keys:
        apiBase: apiBase
        awsAccessKeyId: awsAccessKeyId
        awsSecretAccessKey: awsSecretAccessKey
    liteLLMParams:
      model: "anthropic/claude-opus4.1"
      customLLMProvider: "bedrock"
  - modelName: gpt-4o
    requiresAuth: false
    identifier: gpt-west-eu-prod
    liteLLMParams:
      model: "azure/gpt-4o"
