apiVersion: v1
kind: Secret
metadata:
  name: bedrock-model-credentials
  namespace: litellm
type: Opaque
data:
  awsAccessKeyId: bGl0ZWxsbQ== # base64 encoded value of "litellm"
  awsSecretAccessKey: bGl0ZWxsbQ== # base64 encoded value of "litellm"
  apiBase: aHR0cDovL2xvY2FsaG9zdDo0MDAw #base64 encoded value of http://localhost:4000
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-credentials
  namespace: litellm
type: Opaque
data:
  apiKey: dGVzdC1hcGkta2V5 # base64 encoded value of "test-api-key"
  apiBase: aHR0cDovL2xvY2FsaG9zdDo0MDAw #base64 encoded value of http://localhost:4000