apiVersion: v1
kind: Secret
metadata:
  name: bedrock-model-credentials
  namespace: litellm
type: Opaque
data:
  awsAccessKeyId: bGl0ZWxsbQ== # base64 encoded value of "litellm"
  awsSecretAccessKey: bGl0ZWxsbQ== # base64 encoded value of "litellm"
  apiBase: aHR0cDovL2xvY2FsaG9zdDo0MDAw #base64 encoded value of http://localhost:4000