apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "litellm-operator.fullname" . }}-litellm-model-viewer-role
  labels:
  {{- include "litellm-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - litellm.litellm.ai
  resources:
  - models
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - litellm.litellm.ai
  resources:
  - models/status
  verbs:
  - get
