{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "litellm-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "litellm-operator.fullname" . }}-serving-cert
  labels:
  {{- include "litellm-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "litellm-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-litellm-litellm-ai-v1alpha1-litellminstance
  failurePolicy: Fail
  name: vlitellminstance-v1alpha1.kb.io
  rules:
  - apiGroups:
    - litellm.litellm.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - litellminstances
  sideEffects: None
{{- end }}
