apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "litellm-operator.fullname" . }}-virtualkey-editor-role
  labels:
  {{- include "litellm-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - auth.litellm.ai
  resources:
  - virtualkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.litellm.ai
  resources:
  - virtualkeys/status
  verbs:
  - get
