{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "litellm-operator.fullname" . }}-webhook-service
  labels:
  {{- include "litellm-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app.kubernetes.io/name: litellm-operator
    control-plane: controller-manager
    {{- include "litellm-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
{{- end }}
